# Generated by Django 5.2.1 on 2025-05-12 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date verified"
                    ),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last active"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active user"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified email"),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="admin")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
