# Generated by Django 5.2.1 on 2025-05-12 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("code", models.IntegerField()),
                (
                    "qr_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_available", models.BooleanField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "last_taken_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
